### PR TITLE
Recognize admin authority when selecting individual proposals

### LINKED ISSUE #951: Proposal data is "not found"
I _think_ this might be broken. Locally:

Hitting `http://localhost:3001/proposals?_page=1&_count=100&organization=10` returns:
```json
{
  "entries": [
    {
      "id": 114,
      "versions": [...],
      "createdAt": "2024-04-19T16:32:58.714618-05:00",
      "createdBy": 5,
      "externalId": "2",
      "opportunityId": 54
    },
    {
      "id": 112,
      "versions": [...],
      "createdAt": "2024-04-19T16:32:54.533533-05:00",
      "createdBy": 5,
      "externalId": "2",
      "opportunityId": 53
    }
  ],
  "total": 110
}
```

But then hitting `http://localhost:3001/proposals/114` returns:
```json
{
  "name": "NotFoundError",
  "message": "The proposal was not found (id: 114)",
  "details": [
    {
      "name": "NotFoundError"
    }
  ]
}
```

_Originally posted by @reefdog in https://github.com/PhilanthropyDataCommons/service/issues/932#issuecomment-2071351538_

### PR DESCRIPTION
**Pull request by slifty**
This PR fixes a bug where an admin couldn't access proposal data they didn't own when loading individual proposals

Resolves #951

### CODE REVIEW

File: src/database/operations/assert/assertProposalAuthorization.ts [hunk 1]
```diff
@@ -1,14 +1,18 @@
...
-import type { CheckResult } from '../../../types';
+import type { AuthContext, CheckResult } from '../../../types';
 
 export const assertProposalAuthorization = async (
 	id: number,
-	userId: number,
+	authContext: AuthContext,
 ): Promise<void> => {
+	const { id: userId } = authContext.user;
+	const { isAdministrator } = authContext.role;
```
Comment (reefdog) [inline src/database/operations/assert/assertProposalAuthorization.ts:10]: FWIW, you can do deep destructured assignment more idiomatically like this:
```suggestion
	const { role: { isAdministrator } } = authContext;
```

Comment (slifty) [reply src/database/operations/assert/assertProposalAuthorization.ts:10]: fiiiiiiiiiiiiiiine
